"use client"

import { useState } from "react"
import { Download, FileText, FileSpreadsheet, Check } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { useWallet } from "@/lib/wallet-context"
import { useArcTransactions } from "@/hooks/use-arc-transactions"
import {
  getCategoryBreakdownFromTxs,
  getAnalyticsFromTxs,
} from "@/lib/analytics-from-txs"
import type { NormalizedTransaction } from "@/lib/arcscan-api"

function downloadCSV(transactions: NormalizedTransaction[]) {
  const header = "ID,Date,Amount,Direction,Label,Category,Counterparty\n"
  const rows = transactions
    .map(
      (t) =>
        `${t.id},${new Date(t.date).toISOString()},${t.amount},${t.direction},${t.label},${t.category},${t.counterparty}`
    )
    .join("\n")

  const blob = new Blob([header + rows], { type: "text/csv" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = "arc-transactions.csv"
  a.click()
  URL.revokeObjectURL(url)
}

function downloadMonthlyReport(transactions: NormalizedTransaction[]) {
  const analytics = getAnalyticsFromTxs(transactions)
  const categories = getCategoryBreakdownFromTxs(transactions)
  const incoming = transactions
    .filter((t) => t.direction === "incoming")
    .reduce((s, t) => s + t.amount, 0)
  const outgoing = transactions
    .filter((t) => t.direction === "outgoing")
    .reduce((s, t) => s + t.amount, 0)
  const txCount = transactions.length

  const report = `ARC Finance Monthly Report
================================
Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
Period: From chain data

SUMMARY
-------
Total Transactions: ${txCount}
Total Incoming: $${Math.round(incoming).toLocaleString()}
Total Outgoing: $${Math.round(outgoing).toLocaleString()}
Net Flow: $${Math.round(incoming - outgoing).toLocaleString()}

ANALYTICS
---------
Average Monthly Spending: $${analytics.avgMonthlySpending.toLocaleString()}
Average Incoming Funds: $${analytics.avgIncoming.toLocaleString()}
Largest Transaction: $${analytics.largestTransaction.toLocaleString()}
Most Active Day: ${analytics.mostActiveDay}

SPENDING BY CATEGORY
--------------------
${categories
  .sort((a, b) => b.value - a.value)
  .map((c) => `${c.name}: $${c.value.toLocaleString()}`)
  .join("\n")}

================================
Report generated by Arc Finance Dashboard
`

  const blob = new Blob([report], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = "arc-monthly-report.txt"
  a.click()
  URL.revokeObjectURL(url)
}

export default function ReportsPage() {
  const { isConnected } = useWallet()
  const { transactions, isLoading } = useArcTransactions()
  const [csvDownloaded, setCsvDownloaded] = useState(false)
  const [reportDownloaded, setReportDownloaded] = useState(false)
  const [reportMonth, setReportMonth] = useState("current")

  const incoming = transactions
    .filter((t) => t.direction === "incoming")
    .reduce((s, t) => s + t.amount, 0)
  const outgoing = transactions
    .filter((t) => t.direction === "outgoing")
    .reduce((s, t) => s + t.amount, 0)
  const txCount = transactions.length

  function handleCSV() {
    downloadCSV(transactions)
    setCsvDownloaded(true)
    setTimeout(() => setCsvDownloaded(false), 2000)
  }

  function handleReport() {
    downloadMonthlyReport(transactions)
    setReportDownloaded(true)
    setTimeout(() => setReportDownloaded(false), 2000)
  }

  if (!isConnected) {
    return (
      <div className="flex flex-col gap-6">
        <div>
          <h1 className="font-heading text-2xl font-bold text-foreground">Reports</h1>
          <p className="text-sm text-muted-foreground">Export your data and download reports</p>
        </div>
        <Card>
          <CardContent className="py-16 text-center text-muted-foreground">
            Connect your wallet to export transactions and reports.
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="font-heading text-2xl font-bold text-foreground">Reports</h1>
        <p className="text-sm text-muted-foreground">
          Export your data and download reports
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* CSV Export */}
        <Card>
          <CardHeader>
            <div className="flex items-start gap-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                <FileSpreadsheet className="h-5 w-5 text-primary" />
              </div>
              <div>
                <CardTitle className="font-heading text-lg font-semibold text-card-foreground">
                  Transaction Export
                </CardTitle>
                <p className="mt-1 text-sm text-muted-foreground">
                  Download all {txCount} transactions as a CSV file
                </p>
              </div>
            </div>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <div className="rounded-lg bg-secondary p-4">
              <div className="flex flex-col gap-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Format</span>
                  <span className="font-medium text-card-foreground">CSV</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Rows</span>
                  <span className="font-medium text-card-foreground">{txCount}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Columns</span>
                  <span className="font-medium text-card-foreground">
                    ID, Date, Amount, Direction, Label, Category, Counterparty
                  </span>
                </div>
              </div>
            </div>
            <Button onClick={handleCSV} className="gap-2" disabled={isLoading || txCount === 0}>
              {csvDownloaded ? (
                <>
                  <Check className="h-4 w-4" />
                  Downloaded
                </>
              ) : (
                <>
                  <Download className="h-4 w-4" />
                  Export CSV
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* Monthly Report */}
        <Card>
          <CardHeader>
            <div className="flex items-start gap-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                <FileText className="h-5 w-5 text-primary" />
              </div>
              <div>
                <CardTitle className="font-heading text-lg font-semibold text-card-foreground">
                  Monthly Report
                </CardTitle>
                <p className="mt-1 text-sm text-muted-foreground">
                  Download a summary report for the selected month
                </p>
              </div>
            </div>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <Select value={reportMonth} onValueChange={setReportMonth}>
              <SelectTrigger>
                <SelectValue placeholder="Select month" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="current">Current Month</SelectItem>
                <SelectItem value="previous">Previous Month</SelectItem>
              </SelectContent>
            </Select>

            <div className="rounded-lg bg-secondary p-4">
              <div className="flex flex-col gap-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Total Incoming</span>
                  <span className="font-medium text-primary">
                    +${Math.round(incoming).toLocaleString()}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Total Outgoing</span>
                  <span className="font-medium text-card-foreground">
                    -${Math.round(outgoing).toLocaleString()}
                  </span>
                </div>
                <div className="flex justify-between border-t border-border pt-2">
                  <span className="font-medium text-muted-foreground">Net Flow</span>
                  <span className="font-semibold text-card-foreground">
                    ${Math.round(incoming - outgoing).toLocaleString()}
                  </span>
                </div>
              </div>
            </div>

            <Button onClick={handleReport} className="gap-2" disabled={isLoading || txCount === 0}>
              {reportDownloaded ? (
                <>
                  <Check className="h-4 w-4" />
                  Downloaded
                </>
              ) : (
                <>
                  <Download className="h-4 w-4" />
                  Download Report
                </>
              )}
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* Quick Summary */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="font-heading text-base font-semibold text-card-foreground">
            Quick Summary
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Your wallet processed {txCount} transactions over the last 30 days, with ${Math.round(incoming).toLocaleString()} in incoming funds and ${Math.round(outgoing).toLocaleString()} in outgoing transfers. Your net flow for the period is{" "}
            <span className={incoming > outgoing ? "text-primary font-medium" : "text-destructive font-medium"}>
              ${Math.round(incoming - outgoing).toLocaleString()}
            </span>
            . Download the full CSV or monthly report above for your records.
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
